[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2

[rpc_endpoints]
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

[etherscan]
worldchain_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://worldscan.org" }
